library my_prj.globals;
import 'package:flutter/material.dart';
import '../kupeza.dart';

const kGoogleApiKey = "AIzaSyDEIMjYd-mOfWIulF39YFFYGzIXa5vlU-g";
String url = 'https://kupeza.co.zm/api/newsearcher?location=Lusaka';
String urlloggedin = 'https://kupeza.co.zm/api/newsearcher2?location=Lusaka';
String minprice = '0' ;
String maxprice = '10000000';
String sales ='All';
String props ='All';
String bedrooms ='All';
String order = 'Distance';
String Loc = 'Lusaka';
double kuoloc = 0;
var kupeza = new Kupeza();
var kupimages = new List<String>();
var Authkeys = new List<String>();
String authorization_value ='';
String name ='';
double prices = 0;
List<Kupeza> listOfHomePosts = new List<Kupeza>();
List<Kupeza> listOfFavorites= new List<Kupeza>();
var scroll = 0;
Color mainColor22 = Colors.purple;
Color mainColor = Color.fromRGBO(255,  204, 249, 0.4);
Color mainColor1 = Color.fromRGBO(255, 204, 249, 0.4);
Color mainColor2 = Color.fromRGBO(255, 204, 249, 0.4);
Color mainColor3 = Color.fromRGBO(255, 204, 249, 0.4);
Color mainColor4 = Color.fromRGBO(255, 204, 249, 0.4);
Color mainColor7 = Color.fromRGBO(255, 204, 249, 0.4);
int currentIndex = 0;
Color tabColor1 = Colors.purple;
Color tabColor2 = Color.fromRGBO(74, 77, 75, 0.9);
Color tabColor3 = Color.fromRGBO(74, 77, 75, 0.9);
Color tabColor4 = Color.fromRGBO(74, 77, 75, 0.9);
Color mainColor0 = Colors.purple;
Color mainColor01 = Color.fromRGBO(255, 204, 249, 0.4);
Color mainColor02 = Color.fromRGBO(255, 204, 249, 0.4);
Color textColor0 = Colors.white;
Color textColor01 = Colors.purple;
Color textColor02 = Colors.purple;
Color textColor = Colors.white;
Color textColor1 = Colors.purple;
Color textColor2 = Colors.purple;
Color textColor3 = Colors.purple;
Color textColor4 = Colors.purple;
Color textColor7 = Colors.purple;
var currvalue = 'All';
String selected = "All";
String selectedmin ='K0';
String selectedmax ='K10000000';
String authorization ;
bool valuez = true;
bool valuez1 = false;
bool valuez2 = false;
bool valuez3 = false;